package uz.rakhmonov.i.qatagon_qurbonlari

object Data {
    val infoBehbudiy="Mahmudxoʻja Behbudiy (Kirill alifbosida: Маҳмудхўжа Беҳбудий; Arab alifbosida: محمود خواجه بهبودی\u200E; Toʻliq oti - Mahmudxoʻja Behbudiy ibn Behbudxoʻja) (20-Yanvar 1875 Samarqand — 25-Mart 1919 Qarshi) dramaturg, noshir, din va jamoat arbobi, jadidchilik harakati yetakchilaridan biri. U Yassaviy avlodidan. 18 yoshidan qozixonada mirzalik qiladi, qozi, mufti darajasiga koʻtariladi. Behbudiy haj safarida boʻlgan chogʻida Arabiston, Misr, Turkiyani kezib chiqqan (1899–1900). Sayohat davomida yangi maktab (usuli jadid) ochish fikri mustahkamlanib bordi. Samarqand yaqinidagi Halvoyi qishlogʻida Ajziy, Rajabaminda Abdulqodir Shakuriylar bilan hamkorlikda yangi maktab ochadi. Behbudiy Qozon va Ufaga borib (1903–1904), u yerdagi yangi usul maktablari bilan tanishadi, tatar ziyolilari bilan aloqani yoʻlga qoʻyadi. Yangi maktablar uchun darsliklar tuzishga kirishadi."
    val infoChulpon="Choʻlpon (taxallusi; asl ism-sharifi Abdulhamid Sulaymon oʻgʻli Yunusov) (1897, Andijon — 1938.4.10, Toshkent) — shoir, yozuvchi, dramaturg , tarjimon, tanqidchi va jamoat arbobi. Dastlab, madrasada (1908-1912), soʻngra rus-tuzem maktabida (1912-1914) oʻqigan. Sharq mumtoz shoirlari asarlarini mutolaa qilish va jadid matbuotini kuzatish yoʻli bilan adabiy, ijtimoiy-siyosiy bilimini oshirgan.\n" +
            "\n" +
            "1914-yil Toshkentga kelib, „Sadoi Turkiston“ gazetasi bilan hamkorlik qilgan. „Yangi Sharq“, „Ishtirokiyun“ (1920-yildan „Qizil bayroq“, 1922-yildan „Turkiston“) gazetasida adabiy xodim (1919-1923), Xalq maorif komissarligi qoshidagi Ilmiy kengash (1921-yildan Oʻlka oʻzbek bilim hayʼati, 1922-yildan Ilmiy hayʼat)da rais (1920-1923), „Buxoro axboroti“ gazetasida muharrir (1921-1922), „Turon“ teatrida direktor (1921; 1922-1923), „Mushtum“ jurnali va „Darxon“ gazetasida texnik muharrir, adabiy xodim (1922-1923), Oʻzbek drama studiyasi (Moskva, 1924-1927) va Oʻzbek davlat drama teatrida adabiy emakdosh (1927-1931), SSSR XKS va Sharq xalqlari markaziy nashriyotida tarjimon (Moskva, 1931-1934), „Mushtum“ va „Guliston“ jurnallari hamda „Teatru“ gazetasida adabiy xodim (jamoatchilik asosida, 1935-1937)"
    val infoQodiriy="Abdulla Qodiriy (asosiy taxalluslari: Qodiriy, Julqunboy) (1894.4.10-Toshkent-1938.10.4) – XX a. yangi oʻzbek adabiyotining ulkan namoyandasi, oʻzbek romanchiligining asoschisi; 20-yillardagi muhim ijtimoiy-madaniy jarayonlarning faol ishtirokchisi. Bogʻbon oilasida tugʻilgan. Otasi Qodirbobo (1820–1924) xon, beklar qoʻlida sarbozlik qilgan, rus bosqini paytida (1865) Toshkent mudofaasida qatnashgan. Otasi boshidan oʻtgan sarguzashtlar Abdulla Qodiriyning qator asarlari, xususan tarixiy romanlarining yuzaga kelishida muhim rol oʻynagan. Abdulla Qodiriy musulmon maktabida (1904–06), rus-tuzem maktabida (1908–12), Abulqosim shayx madrasasida (1916–17) taʼlim oldi; Moskvadagi adabiyot kursida (1925–26) oʻqidi. Yoshligidanoq qadimgi Sharq madaniyati va adabiyoti ruhida tarbiya topgan; arab, fors va rus tillarini oʻrgangan. Jahon adabiyotini ixlos bilan mutolaa qilgan.\n" +
            "\n" +
            "Abdulla Qodiriyning ulkan merosi haligacha kitobxonlar qalbidan joy olmoqda."
    val infoFitrat="Abdurauf Fitrat (1886, Buxoro shahri, Buxoro amirligi — 4-oktabr, 1938, Toshkent shahri, Oʻzbekiston SSR) — oʻzbek tarixchisi, filolog, tarjimon, yozuvchi, dramaturg va shoir, zamonaviy oʻzbek tili va adabiyoti asoschilaridan biri, Oʻrta Osiyo jadidchiligining taniqli vakillaridan biri, birinchi oʻzbek professori[1] (1926). Jadidchilik milliy maʼrifatparvarlik harakatining tarafdori. Turkiyada oʻqigan. Inqilobga qadar Oʻrta Osiyoni Rossiyadan ozod qilinishi harakatlarida faol qatnashgan, politsiya nazorati ostida boʻlgan. Turkiyadagi „Yosh turklar“ harakatidan ilhomlanib, Buxoroda „Yosh buxoroliklar“ partiyasini tuzgan, uning maʼnaviy rahnamosiga aylangan. Doʻsti va maslakdoshi Munzim bilan hamkorlikda buxorolik 70 nafar yosh turkistonliklarni Germaniyaning bir qator oliy taʼlim muassasalariga oʻqishga yuborgan (1922)[2]."
    val infoNosir="Usmon Nosir (1912–1944) — XX asr oʻzbek sheʼriyatiga chaqmoqdek kirib kelgan va yashindek qisqa ijodiy umr kechirgan shoir. Usmon Nosir 1912-yilning 13-noyabrida Namanganda tugʻildi.\n" +
            "\n" +
            "Otasidan yetim qolgan Usmon Nosir Qoʻqondagi bolalar uyida tarbiyalanadi. Isteʼdodli oʻsmir u yerda rus va jahon adabiyotining sara namunalari bilan tanishadi. Internatni bitirgach, 1931-yildan Samarqanddagi Oʻzbekiston davlat universiteti (OʻzDU) ning filologiya fakultetida oʻqidi.\n" +
            "\n" +
            "Bolaligidan sheʼrlar yoza boshlagan Usmon Nosir badiiy ijod bilan bor yoʻgʻi oʻn besh yilgina, yaʼni qamoqqa olinguncha astoydil shugʻullandi. Shu fursatda oʻzining qanchalik nodir isteʼdodga ega ekanligini yaqqol koʻrsatdi. Yosh shoirning „Quyosh bilan suhbat“ (1932), „Safarbar satrlar“ (1932), „Traktorobod“ (1934), „Yurak“ (1935), „Mehrim“ (1935) kabi sheʼriy toʻplamlari hamda „Norboʻta“ (1932) va „Naxshon“ (1935) kabi dostonlari va „Atlas“, „Zafar“, „Soʻnggi kun“, „Dushman“ kabi dramalari bosildi. Usmon Nosir 1937-yilning 14-iyulida „xalq dushmani“ sifatida qamoqqa olindi va Toshkent, Magadan, Kemerovo turmalarida yotdi. Qamoqda inson bolasi chidashi mumkin boʻlmaydigan qiynoqlarga duchor boʻlgan shoir 1944-yilda Kemerovoda halok boʻldi. Usmon Nosir oʻzbek sheʼriyatiga yangi ohang, yangi ruh, yangi obrazlar olib kirdi. U sheʼrlarida alangali tuygʻularini jilovlamas, dilida kechayotgan tugʻyonlarni susaytirmas, inson ruhiy dunyosini poʻrtanalar ichida koʻrsatardi. "
}